### ISSUE TITLE
leapp update failed on “check_installed_kernels”

### ISSUE THREAD

**Issue by Xingeqwd** [oamg/leapp-repository#1013]
Hello, i got some problem here

When i using the “leapp upgrade” on my Centos7.9
(roughly in accordance with [this guidance of almaLinux](https://wiki.almalinux.org/elevate/ELevate-quickstart-guide.html) to transfrom my system to almalinux),
this's  always return a error of
 "[ERROR] Actor: check_installed_kernels   Message: Cannot find any installed kernel signed by Red Hat." like the photo below
![image](https://user-images.githubusercontent.com/46107662/214789259-6449c85e-98a4-4863-a708-05a8f79ebb31.png)

But my kernels are all normal, pure and latest kernal without any unmodified
(kernel list like the photo showned below)
![image](https://user-images.githubusercontent.com/46107662/214789318-ba37c981-fff9-4931-a5fd-9dc2970b7f4a.png)

After various try, test and found, (https://access.redhat.com/discussions/6965486).I could only found that my issue should be same as
"[this redhat discuss](https://access.redhat.com/discussions/6965486)".
(The screenshot of the overview is as follows)
![image](https://user-images.githubusercontent.com/46107662/214790103-34753ff7-69d7-406c-9d57-0988f53e0fb8.png)

But i really didn't understand what he saying of  "After checking the checkinstalledkernels actor, it seems that the name of the kernel should be kernel-core instead. Manually fix the name, and the check passed."

Actually, except this the elapp also made several mistakes(for example the mistake of:
"Detected multiple physical network interfaces where one or more use kernel naming"), 
these were all be solved, but only this can't be solved.

Could someone help me please? Or any ideas are welcome!
Thanks a lot to everyone for your generous help!
Wish you have a good day.

**Comment by pirat89** [comment]
Hi @Xingeqwd \o, the problem is that you are not using official native kernel packages for the particular distro, but `kernel-ml` instead, which we do not support for the upgrade. You need to install and boot to the official CentOS kernel prior the upgrade to fix it, or you can go on your own and remove the `checkinstalledkernels` actor.

**Comment by Xingeqwd** [comment]
==update after about 2 hours==
I found that there is a path that stores a lot of actor's python scripts,But still did not find the actor file of checkinstalledkernels
(this guy seems to be composed of multiple separate actors),
so still can't disable it

**Comment by pirat89** [comment]
@Xingeqwd  No sure how the package is called in your case so you could do just something like:
```
rpm -ql <your-rpm-name> | grep checkinstalledkernels
```
and remove the whole directory with the `actor.py` inside. In my case it's e.g.
```
rm -rf /usr/share/leapp-repository/repositories/system_upgrade/common/actors/kernel/checkinstalledkernels
```

**Comment by Xingeqwd** [comment]
> @Xingeqwd No sure how the package is called in your case so you could do just something like:
> 
> ```
> rpm -ql <your-rpm-name> | grep checkinstalledkernels
> ```
> 
> and remove the whole directory with the `actor.py` inside. In my case it's e.g.
> 
> ```
> rm -rf /usr/share/leapp-repository/repositories/system_upgrade/common/actors/kernel/checkinstalledkernels
> ```

@pirat89  Thanks! after proceed these command, the actor file in the /checkinstalledkernels folder did get empty

My search path before these was "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/...", 
my path was wrong, no wonder I couldn’t find it

I thought, the checkinstalledkernels problem should be the last problem I turn to almaLinux. (after solved so so much problems)
In this way, "checkinstalledkernels" should be disabled.

I am peocessing the "leapp update" command, hope this time it will goes more smoother in this time.

By the way, I also posted a post on the Centos forum last night, but the moderator over there seems to have not passed the review of my post. It is really "leapp" that is better!

And, thanks, thanks again! 
Wish you a good good day!

**Comment by Xingeqwd** [comment]
After that, I encountered two or three problems, but fortunately, they were solved through a combination of logs and networks.
Now there is another problem that doesn't seem to be easy to deal with, so I have to raise another issue. . .
