### ISSUE TITLE
Reply > leapp update failed on “check_installed_kernels”

### ISSUE THREAD

**Issue by Xingeqwd** [oamg/leapp-repository#1014]
I don't know how to cancel the "cancel" operation done by the moderator, So I have to open another post.
Express my sorry if I caused any trouble

Thank you for your help, As your guidance, I want to use the latter approach.
But there are still something that I don't understand:
  How to delete the actor of checkinstalledkernels?
    Is these to modifies the script of "leapp upgrade"? Which file should I modify please?

Thank you again, I really don't know enough on this aspect.
Wish you have a good day

> Hi @Xingeqwd \o, the problem is that you are not using official native kernel packages for the particular distro, but `kernel-ml` instead, which we do not support for the upgrade. You need to install and boot to the official CentOS kernel prior the upgrade to fix it, or you can go on your own and remove the `checkinstalledkernels` actor.

_Originally posted by @Xingeqwd in https://github.com/oamg/leapp-repository/issues/1013#issuecomment-1404801841_

**Comment by Xingeqwd** [comment]
(duplicated with https://github.com/oamg/leapp-repository/issues/1013)

**Comment by pirat89** [comment]
@Xingeqwd  No sure how the package is called in your case so you could do just something like:
```
rpm -ql <your-rpm-name> | grep checkinstalledkernels
```
and remove the whole directory with the `actor.py` inside. In my case it's e.g.
```
rm -rf /usr/share/leapp-repository/repositories/system_upgrade/common/actors/kernel/checkinstalledkernels
```
