### ISSUE TITLE
"leapp update" failed on python problem after downloading pacages

### ISSUE THREAD

**Issue by Xingeqwd** [oamg/leapp-repository#1016]
**Foreword**
Hello there, it's me again....
After sloving nearly ten problems, here comes a another problem here but i cant handle
So I have to came here to seeking for help
</br>
**Condition overview**
When i processing the “leapp upgrade” on my Centos7.9
(roughly in accordance with [this guidance of almaLinux](https://wiki.almalinux.org/elevate/ELevate-quickstart-guide.html) to transfrom my system to almalinux),
It always return error like this(seems like a python programical problem    _like picture showned below_)
![image](https://user-images.githubusercontent.com/46107662/214871412-6047ab4c-d1a9-4b7d-973f-6896730c155a.png)
That's so strange, right? Normally, this shouldn't have this kind of problem appeared.......
</br>
**Tried of solution**
(Similar problems have occurred before, but it should be a problem with my local python, and it will be solved after reinstalling)
like [this github link](https://github.com/certbot/certbot/issues/7645) showned
In this time, these method(and similar) seems useless
After researching the log and founding in multiple ways, there is still no result, so I came to ask
</br>
**Files**
i thought these haven't sensitive content in it, for the sake of convenience, I put them up:
[leapp-report.txt](https://github.com/oamg/leapp-repository/files/10510659/leapp-report.txt)
[leapp-upgrade.log](https://github.com/oamg/leapp-repository/files/10510668/leapp-upgrade.log)
</br>
**Afterword**
Could someone help me please? Or any ideas are welcome!
Thanks a lot to everyone for the generous help and patient reading!
Wish you all have a good good day.

**Comment by pirat89** [comment]
This one is specific to the elevate project as the problematic line is not present in upstream: https://github.com/oamg/leapp-repository/blob/cdbbb83e0a52d4e6a84281dad19a7520ce1115b7/repos/system_upgrade/common/libraries/dnfplugin.py#L218

Obviously, they tried to fix a different issue that occured, but they do not check whether they can call the encode method on the object. Also, it seems to me as wrong place to try to handle this here as this should be treated most likely in the framework itself.

Regarding that, I have to close it as this issue is not present in the upstream project. You need to search in forums / ticket system / ... of almalinux or the Elevate project.

**Comment by Xingeqwd** [comment]
> 这是 elevate 项目特有的，因为上游不存在问题行：
> 
> https://github.com/oamg/leapp-repository/blob/cdbbb83e0a52d4e6a84281dad19a7520ce1115b7/repos/system_upgrade/common/libraries/dnfplugin.py#L218
> 
> 显然，他们试图修复发生的另一个问题，但他们没有检查是否可以在对象上调用编码方法。此外，在我看来，尝试在此处处理此问题是错误的地方，因为这最有可能在框架本身中进行处理。
> 
> 关于这一点，我必须关闭它，因为上游项目中不存在这个问题。您需要在 almalinux 或 Elevate 项目的论坛/票务系统/...中搜索。

okay then, you are right, this should be a problem of almalinux,
i will seek almalinux for help

> This one is specific to the elevate project as the problematic line is not present in upstream:
> 
> https://github.com/oamg/leapp-repository/blob/cdbbb83e0a52d4e6a84281dad19a7520ce1115b7/repos/system_upgrade/common/libraries/dnfplugin.py#L218
> 
> Obviously, they tried to fix a different issue that occured, but they do not check whether they can call the encode method on the object. Also, it seems to me as wrong place to try to handle this here as this should be treated most likely in the framework itself.
> 
> Regarding that, I have to close it as this issue is not present in the upstream project. You need to search in forums / ticket system / ... of almalinux or the Elevate project.

okay then, you are right, this should be a problem of almalinux,
i will seek almalinux for help

haha, no metter what, thank you!

**Comment by pirat89** [comment]
You are welcome \o
