### ISSUE TITLE
pes-events.json license

### ISSUE THREAD

**Issue by andrewlukoshko** [oamg/leapp-repository#1102]
I know that in the past `pes-events.json` file was only available with Red Hat Subscription.
Now it's the part of this git repo, but header still says:
```
"legal_notice": "Copyright 2018 Red Hat, Inc. This file is provided to customers as a part of the Servicesunder the Red Hat Enterprise Agreement and not for redistribution.",
```
But repo content is licensed under Apache 2.0 which clearly allows to redistribute.
Is it possible to fix this header to match repo license?

**Comment by andrewlukoshko** [comment]
@pirat89 could you check this one please?

**Comment by pirat89** [comment]
@pirat89 I do not want to take care about this any time soon. Also to my knowledge, data files cannot be licensed so the header should not have any effect. we will discuss it in a team when we have a time

**Comment by Rezney** [comment]
@andrewlukoshko Hello, thanks for reaching out. We are currently discussing this and I will update you as soon as I have something.

**Comment by andrewlukoshko** [comment]
I see that latest pes-events.json doesn't contain `legal_notice`.

**Comment by pirat89** [comment]
@andrewlukoshko  yes, closing the issue.
