### ISSUE TITLE
Unexpected format of target version: 7

### ISSUE THREAD

**Issue by anderbubble** [oamg/leapp-repository#1126]
**Actual behavior**

```
$ sudo leapp preupgrade

Error: Unexpected format of target version: 7
```

**To Reproduce**

1. installed `leapp-upgrade-el7toel8` and `leapp-upgrade-el7toel8-deps` on CentOS 7, as built from master
2. `leapp preupgrade`

**Expected behavior**

It should detect CentOS 7.9. It looks like it's reading `/etc/os-release` to determine the _source_ version, but since `VERSION_ID="7"` it's breaking. (The error message indicating "target" version is erroneous.) `/etc/os-release` doesn't provide any version number in the form of `x.y`, though `/etc/system-release` _kind of_ does. (`7.9.2009`)

I started working on a patch to allow it to support an environment variable to override the detected version (e.g., to explicitly specify 7.9) but I wanted to check if there is something I'm missing first.

**System information:**

- OS and version: `CentOS Linux release 7.9.2009 (Core)`
- `Linux centos7 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- `leapp-deps-0.16.0-100.202309010036Z.b57c5de.master.el7.noarch`
- `leapp-0.16.0-100.202309010036Z.b57c5de.master.el7.noarch`
- `python2-leapp-0.16.0-100.202309010036Z.b57c5de.master.el7.noarch`
- `leapp-upgrade-el7toel8-0.19.0-100.202309010124Z.2ba147c.master.el7.noarch`
- `leapp-upgrade-el7toel8-deps-0.19.0-100.202309010124Z.2ba147c.master.el7.noarch`

(These hashes represent a single commit to leapp-repository that I made trying to fix this behavior. Same behavior at `93c6fd4f150229a01ba43ce74214043cffaf7dce`.

[leapp-logs.tar.gz](https://github.com/oamg/leapp-repository/files/12492132/leapp-logs.tar.gz)

**Comment by anderbubble** [comment]
Here's the patch I was working on as an experiment, in case it's useful information.

```
diff --git a/commands/command_utils.py b/commands/command_utils.py
index 338978d..5606cd8 100644
--- a/commands/command_utils.py
+++ b/commands/command_utils.py
@@ -65,6 +65,13 @@ def get_upgrade_flavour():
     return LEAPP_UPGRADE_FLAVOUR_DEFAULT
 
 
+def get_source_version():
+    if 'LEAPP_SOURCE_VERSION' in os.environ:
+        return os.environ['LEAPP_SOURCE_VERSION']
+    else:
+        return get_os_release_version_id('/etc/os-release')
+
+
 def get_os_release_version_id(filepath):
     """
     Retrieve data about System OS release from provided file.
@@ -101,13 +108,13 @@ def get_supported_target_versions(flavour=get_upgrade_flavour()):
     The default value for `flavour` is `default`.
     """
 
-    current_version_id = get_os_release_version_id('/etc/os-release')
-    target_versions = get_target_versions_from_config(current_version_id, flavour)
+    source_version = get_source_version()
+    target_versions = get_target_versions_from_config(source_version, flavour)
     if not target_versions:
         # If we cannot find a particular major.minor version in the map,
         # we fallback to pick a target version just based on a major version.
         # This can happen for example when testing not yet released versions
-        major_version = get_major_version(current_version_id)
+        major_version = get_major_version(source_version)
         target_versions = get_target_versions_from_config(major_version, flavour)
 
     return target_versions
diff --git a/commands/upgrade/util.py b/commands/upgrade/util.py
index b52da25..3871d1a 100644
--- a/commands/upgrade/util.py
+++ b/commands/upgrade/util.py
@@ -221,9 +221,9 @@ def prepare_configuration(args):
     os.environ['LEAPP_UPGRADE_PATH_TARGET_RELEASE'] = target_version
     os.environ['LEAPP_UPGRADE_PATH_FLAVOUR'] = flavor
 
-    current_version = command_utils.get_os_release_version_id('/etc/os-release')
+    source_version = command_utils.get_source_version()
     os.environ['LEAPP_IPU_IN_PROGRESS'] = '{source}to{target}'.format(
-        source=command_utils.get_major_version(current_version),
+        source=command_utils.get_major_version(source_version),
         target=command_utils.get_major_version(target_version)
     )
 

```

**Comment by andrewlukoshko** [comment]
@anderbubble original Leapp doesn't support CentOS.
You can try ELevate project based on Leapp but with necessary patches to support non-RHEL OS
https://wiki.almalinux.org/elevate/

**Comment by fernflower** [comment]
@anderbubble As Andrew has stated above, leapp does not support CentOS and there are no plans to change that. Please look into ELevate.
