### ISSUE TITLE
OL7 to OL8 upgrade fails on scan_source_kernel

### ISSUE THREAD

**Issue by gwynbleidd92** [oamg/leapp-repository#1288]
Hi! Trying to perform migration and upgrade from CentOS7 to OL8.
Sucessfully migrated from CentOS to OL via this guide ([https://docs.oracle.com/en/learn/switch_centos7_ol7/#introduction](https://docs.oracle.com/en/learn/switch_centos7_ol7/#introduction)).
But attempt to upgrade from OL 7.9 to OL 8 fails with error "Unable to obtain kernel information of the booted kernal: no package is providing the booted kernel release returned by uname" in actor "scan_source_kernel".

**System information :**

- OS and version: (Oracle Linux 7.9)
- `# uname -a` 5.4.17-2136.334.6.1.el7uek.x86_64
- `# rpm -qa "*leapp*"`:

```
leapp-upgrade-el7toel8-deps-0.19.0-7.1.el7.noarch
leapp-upgrade-el7toel8-0.19.0-7.1.el7.noarch
leapp-data-oraclelinux-0.2-15.el7.20230823.noarch
leapp-0.16.0-2.el7.noarch
leapp-deps-0.16.0-2.el7.noarch
```

![report plus kernel info](https://github.com/user-attachments/assets/4de625fc-f5d0-4410-a232-b75269f7cc3b)

**Comment by gwynbleidd92** [comment]
> Hi @gwynbleidd92, thank you for the report, but I think that you want to report this issue
> 
>     * on the Elevate project (in case you are using Elevate)
> 
>     * or for Oracle support / Oracle Linux  (in case you are using leapp-upgrade* rpms provided by Oracle)
> 
> 
> Note this project is currently delivering solution for RHEL systems and we do not do any testing on other distributions. However, in case you provide us more information, we could take a look at the code to see if we find the problem. this is no promise we will fix it in upstream, as it's possible the problem could be caused by missing (or unexpected) virtual provides of the kernel-uek rpm in OL.
> 
> Install please the leapp-inspector script (it's one python script file) on the machine, see:
> 
>     * https://github.com/oamg/snippets/tree/main/scripts/leappinspector
> 
> 
> And share please output of following commands (you might want to update shebang or execute it directly with python2):
> 
>     * `python2 leapp-inspector actors --actor scan_source_kernel`
> 
>     * ` leapp-inspector messages --type KernelInfo`

@pirat89 thanks a lot, you pointed me in right direction!
My mistake was in using Leapp from AlmaLinux repo instead of one from OL repo. So, in my case to resolve the issue required steps are:
```
1) yum remove leapp*
2) remove/disable AlmaLinux repo
3) yum install leapp --enablerepo=ol7_leapp,ol7_latest
```

**Comment by gppe66** [comment]
Hello pirat89,
I got same problem of gwynbleidd92. But my repository are correct, better my machine is without internet access, so I downloaded leapp pkgs and installed. I execute python script leapp-inspector you provide, this is the output you ask:

![image](https://github.com/user-attachments/assets/4ffb734b-2a92-4b15-bfb5-bd142029e9b3)

![image](https://github.com/user-attachments/assets/cd5edabe-3629-4981-8e3c-1190552c5346)


while the other command need python3 unavailble on my machine, 

![image](https://github.com/user-attachments/assets/fc03328f-4b4c-4d65-9039-cfab2ca5eba4)

any help will be appreciate,
thanks in advance,

gppe66

**Comment by pirat89** [comment]
Hi @gppe66 , the script is py2 & py3 compatible. it needs to be called with python2 interpreter like in the first case. My mistake that I forgot to append the prefix in that one. I am usually updating the script on my system to be executed by py2 automatically. Nevermind, I do not need the output of the last command in your case.

Can you share output of following commands? Use please a txt file instead of screenshots if possible.

```shell
cat /etc/system-release
rpm -qa "*leapp*"
rpm -qa "kernel*"
rpm -q --provides kernel-3.10.0-862.11.6.el7.x86_64
rpm -q --provides kernel-3.10.0-1062.9.1.el7.x86_64
rpm -q --provides kernel-3.10.0-1160.el7.x86_64
```

**Comment by gppe66** [comment]
Hi Pirat89,
thanks for support, unfortunatly I done rollback after last error I show above on kernel version, unabled to resolve, however my /etc/system-release was 
Oracle Linux Server release 8.10
while my kernel release before do rollback was kernel-uek-4.1.12-124.19.4.el7uek.x86_64 (maybe the Unbreakble Enterprise Kernel caused my failure?)
I can provide you following informations because before this production system I already upgraded development (online I mean going to internet) and test systems (installing this pkgs:
[root@xxxxxxc ~]# rpm -qa | grep -i leapp
leapp-upgrade-el7toel8-0.20.0-2.0.3.el7_9.noarch
python2-leapp-0.17.0-1.0.2.el7_9.noarch
leapp-0.17.0-1.0.2.el7_9.noarch
leapp-deps-el8-5.0.8-100.202401121819Z.0e51aebb.master.el8.noarch
leapp-repository-deps-el8-5.0.8-100.202401121819Z.0e51aebb.master.el8.noarch
[root@xxxxxxxc ~]#
In production I have to upgrade system in offline way, so I dowloaded all al leapp pkgs from Oracle site and create a locally LEAPP repository on different machine.
After the first half of january 2025 I will repeat the upgrade, if you read me again mean I need yet support.
have good Christmas holidays, 
bye
gppe66

**Comment by pirat89** [comment]
> (maybe the Unbreakble Enterprise Kernel caused my failure?)

@gppe66 possibly. I mean, for sure from our POV it's "incorrectly" packaged kernel rpm. In case of OL, you have to use modified packages where OL handles this difference (if they not, I suggest to open bug report for that leapp-upgrade-el7toel8 rpm on OL so they update their product accordingly). We do not plan to cover this one specific difference as we do not use OL and it would need more work for us to come up with a solution that is safe to use across several versions of systems and several distros, than for oracle to add one line into the kernel specfile to be compatible with Centos / CentosStream and RHEL from this point.

**Comment by omnibaer** [comment]
I ran into this issue updating Alma from 8.10 to 9.5. The "kernel-uname-r" binary is provided by the kernel-core or kernel-debug-core package directly. I tried reinstalling kernel-core, restarted, then ran leapp checks again. Same error.

It seems that the rpm command used by scan_source_kernel finds kernel-uname-r but not kernel-rt-uname-r. Also yum provides fails to find anything that provides kernel-rt-uname-r.

Are both required for the update? Or just one or the other?

`2025-04-10 08:45:27.932 INFO     PID: 168097 leapp.workflow.FactsCollection: Executing actor scan_source_kernel 
2025-04-10 08:45:28.49  DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has started: ['rpm', '-q', '--whatprovides', 'kernel-uname-r']
2025-04-10 08:45:28.209 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: kernel-core-4.18.0-553.47.1.el8_10.x86_64
2025-04-10 08:45:28.217 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has finished: ['rpm', '-q', '--whatprovides', 'kernel-uname-r']
2025-04-10 08:45:28.218 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has started: ['rpm', '-q', '--whatprovides', 'kernel-rt-uname-r']
2025-04-10 08:45:28.234 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: no package provides kernel-rt-uname-r
2025-04-10 08:45:28.236 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: Command ['rpm', '-q', '--whatprovides', 'kernel-rt-uname-r'] failed with exit code 1.
2025-04-10 08:45:28.238 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has finished: ['rpm', '-q', '--whatprovides', 'kernel-rt-uname-r']
2025-04-10 08:45:28.239 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has started: ['rpm', '-q', '--provides', 'kernel-core-4.18.0-553.47.1.el8_10.x86_64']
2025-04-10 08:45:30.340 DEBUG    PID: 171827 leapp.workflow.FactsCollection.scan_source_kernel: External command has finished: ['rpm', '-q', '--provides', 'kernel-core-4.18.0-553.47.1.el8_10.x86_64']`

**Comment by pirat89** [comment]
@omnibaer  can you share output of this command?
```
rpm -q --provides kernel-core-4.18.0-553.47.1.el8_10.x86_64
```

**Comment by omnibaer** [comment]
[kernel-core-provides.txt](https://github.com/user-attachments/files/19710951/kernel-core-provides.txt)

Attached, thanks. Let me know if you need anything else!

**Comment by pirat89** [comment]
@omnibaer just to be sure I understand it right, are you actually blocked to upgrade because of the error msg `Unable to obtain kernel information...` or are you just concerned about the debug logs?

**Comment by omnibaer** [comment]
Running `leapp upgrade` results in the same error and the upgrade fails. Thanks

**Comment by pirat89** [comment]
@omnibaer thanks for the confirmation. in such a case most likely I would need more data as I have not been able to reproduce this problem on RHEL - with the same nevra kernel actually. From the shared `provides` it seems everything is ok unless I missed something. It seems to me that most likely it's almalinux / elevate specific, but I cannot say that for 100% without more data. Open please a new issue, providing requested data - for sure:
* `/var/log/leapp/leapp-*log` file

And share there please also following output:
```
md5sum /usr/share/leapp-repository/repositories/system_upgrade/common/libraries/kernel.py /usr/share/leapp-repository/repositories/system_upgrade/common/actors/scansourcekernel/libraries/scan_source_kernel.py
```
