### ISSUE TITLE
kernel-rpm-macros fails transaction

### ISSUE THREAD

**Issue by bocekm** [oamg/leapp-repository#130]
**Actual behavior**
We have redhat-rpm-config in /etc/leapp/transaction/to_remove meaning that it is always removed. But this package is required by kernel-rpm-macros, so the transaction fails if kernel-rpm-macros is installed:
```
Error: 
 Problem 1: cannot install the best candidate for the job
  - conflicting requests
 Problem 2: package kernel-rpm-macros-116-1.el8.noarch requires redhat-rpm-config >= 13, but none of the providers can be installed
  - cannot install the best candidate for the job
  - conflicting requests
```

**To Reproduce**
Steps to reproduce the behavior
1. install kernel-rpm-macros
1. run leapp upgrade --debug
1. See error

**Expected behavior**
Transaction does not fail with kernel-rpm-macros installed. It can be done by adding it to the  to_remove file as well.

**Comment by bocekm** [comment]
It'd be better to rather remove the redhat-rpm-config from the to_remove.
```
 Problem 11: package python2-devel-2.7.15-21.module+el8+2540+b19c9b35.x86_64 requires redhat-rpm-config, but none of the providers can be installed
  - package python2-numpy-f2py-1:1.14.2-9.module+el8+2540+b19c9b35.x86_64 requires python2-devel, but none of the providers can be installed
  - package redhat-rpm-config-116-1.el8.noarch requires perl-srpm-macros, but none of the providers can be installed
  - redhat-rpm-config-9.1.0-87.el7.noarch does not belong to a distupgrade repository
  - conflicting requests
```

**Comment by pirat89** [comment]
This would be possible only with the https://github.com/oamg/leapp-repository/pull/44 PR, otherwise installation fails.
