### ISSUE TITLE
leapp is stuck with a centos 7 suse liberty linux server

### ISSUE THREAD

**Issue by r4han85** [oamg/leapp-repository#1320]
**Actual behavior**
Leapp seems incompatible with a centos 7 with suse liberty linux support activated

**To Reproduce**

a centos 7 box, with suse liberty's last kernel installed (current is 3.10.0-1160.125.1.el7.x86_64 )

1. install '...'
2. setup '....'
3. run '....'
   (when run `leapp`, use always the `--debug` option to provide more data)

**Expected behavior**

**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
- `# uname -a`
```
 Linux myc7box 3.10.0-1160.125.1.el7.x86_64 oamg/leapp#1 SMP Wed Oct 2 17:24:35 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):
```
leapp-data-almalinux-0.4-12.el7.20240827.noarch
leapp-deps-0.18.0-1.el7.noarch
leapp-upgrade-el7toel8-deps-0.21.0-2.el7.elevate.4.noarch
leapp-upgrade-el7toel8-0.21.0-2.el7.elevate.4.noarch
leapp-0.18.0-1.el7.noarch
```

Attach (or provide link to) log files if applicable (optional - may contain confidential information):

- *All files in /var/log/leapp/*
- */var/lib/leapp/leapp.db*
- *journalctl*
- If you want, you can optionally send anything else would you like to provide (e.g. storage info)
log files attached later
**For your convenience you can pack all logs with this command:**

`# tar -czf leapp-logs.tgz /var/log/leapp /var/lib/leapp/leapp.db`

Then you may attach only the `leapp-logs.tgz` file.

****

**Additional context**

**Comment by r4han85** [comment]
Ok, thanks for your reply, and sorry for the inconvenience!

**Comment by pirat89** [comment]
no problem at all :)
