### ISSUE TITLE
Invalid SELinux model and provided information in case of disabled selinux

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp-repository#20]
The `SELinux` model does not reflect correctly what information we can get about SElinux with various setup. E.g. in case SElinux is disabled, we cannot get information about runtime mode (just `None`). Policy cannot contain whatever string. It can contain only these values:
- **targeted** - Targeted processes are protected,
- **minimum** - Modification of targeted policy. Only selected processes are protected. 
- **mls** - Multi Level Security protection.

Regarding the `/etc/selinux/config` file. The model will be changed partially by the PR I will add here later just to fix broken tests. Proper fix will be still need.

- [x] resolve issue
- [x] write tests

**Comment by pirat89** [comment]
Possible solution would be detection of disabled selinux in the [get_selinux_status](https://github.com/oamg/leapp-repository/blob/99049192172b1af21f7c2a7b4f9dc83cfd6ceda1/repos/system_upgrade/el7toel8/actors/systemfacts/libraries/systemfacts.py#L207) function and in such case return SELinux object with values reflecting the state.

**Comment by radomil** [comment]
This issue is addressed in #27

**Comment by radomil** [comment]
This issue has been fixed by above mentioned PR #27 merge and tests were covered by PR #56 merge.
