### ISSUE TITLE
Create tests for peseventscanner

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp-repository#22]
Current tests for the peseventscanner are disabled now as the expected file is currently empty and the tests cannot be proccesed correctly. In all cases, tests are not sufficient. Create tests and modify actor if needed, to proove its valid implementation.

**Comment by bocekm** [comment]
There's many and sufficient tests for peseventsscanner now: https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/el7toel8/actors/peseventsscanner/tests/unit_test.py
