### ISSUE TITLE
`rhsm release --unset` in initramdisk

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp-repository#23]
We hitting issue now because the network is down and rhsm is trying to connect to the server. We need to fix it properly to be able to do upgrades when people have set the release and do not block upgrades at all.

**Comment by vinzenz** [comment]
We'll close this, because it's not going to happen anyway - But we'll take care of it in the FirstBoot phase

**Comment by pirat89** [comment]
Will be resolved by https://github.com/oamg/leapp-repository/pull/260
