### ISSUE TITLE
upgrade initramfs entry cannot be found by grubby

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp-repository#242]
**Actual behavior**
After running `leapp --upgrade`, `grubby --info=DEFAULT` cannot find the newly added kernel, exiting with 1 and printing `grubby: kernel not found`.

**To Reproduce**

    leapp --upgrade
    grubby --info=DEFAULT

**Expected behavior**
Newly added entry

**System information (please complete the following information):**

RHEL-7.6 and _leapp-repository-0.7.0-1.201906101721Z.8ebef3f.master.el7_6.noarch_

****

**Additional context**

Likely caused by #238 plus a likely bug in grubby.  #238 actually added quotes around the entry title text, which results in a technically valid name but this could have broken subsequent grubby call.

I'm not sure if the upgrade is affected; it could be just the grubby bug.

**Comment by bocekm** [comment]
Or another possible cause: EFI+BIOS https://bugzilla.redhat.com/show_bug.cgi?id=1718161#c5

**Comment by AloisMahdal** [comment]
Well it's not an EFI system...
