### ISSUE TITLE
persistentnetnamesconfig ifaces sorting

### ISSUE THREAD

**Issue by shaded-enmity** [oamg/leapp-repository#317]
`sorted` does not sort in place but returns a sorted list.

@msekletar Is sorting really necessary? It looks like nothing in there is really order-dependent.

https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/el7toel8/actors/persistentnetnamesconfig/actor.py#L52

**Comment by msekletar** [comment]
You are right. Calls to sorted() are probably some remnants from the early version of the code. Feel free to delete them. Thanks!

**Comment by shaded-enmity** [comment]
Thanks @msekletar !
