### ISSUE TITLE
repository messes with import hooks

### ISSUE THREAD

**Issue by pemensik** [oamg/leapp-repository#365]
**Actual behavior**
Repository messes badly with import paths. It forces scripts inside git repository to use import leapp. It it is not fully configured (because Fedora 29 is not fully supported), even scripts that do not import any part of leapp modules fail.

Stop that. It complicates debugging of library parts on host machine. Moving the same file outside repository seems lame.

**To Reproduce**
Steps to reproduce the behavior

1. git clone https://github.com/oamg/leapp-repository.git
2. cd leapp-repository
3. (touch empty.py && pytest empty.py; rm empty.py)
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/leapp/models/__init__.py", line 177, in resolve
INTERNALERROR>     cls._resolved = globals()[cls._referenced]
INTERNALERROR> KeyError: 'ReportReference'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/_pytest/main.py", line 176, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/leapp-repository/conftest.py", line 31, in pytest_sessionstart
INTERNALERROR>     repo.load()
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/leapp/repository/manager.py", line 103, in load
INTERNALERROR>     resolve_model_references()
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/leapp/models/__init__.py", line 192, in resolve_model_references
INTERNALERROR>     reference.resolve()
INTERNALERROR>   File "/usr/lib/python3.7/site-packages/leapp/models/__init__.py", line 179, in resolve
INTERNALERROR>     raise ModelDefinitionError('Undefined Model "{}"'.format(cls._referenced))
INTERNALERROR> leapp.exceptions.ModelDefinitionError: Undefined Model "ReportReference"
```

**Expected behavior**
```
=================================================== test session starts ===================================================
platform linux -- Python 3.7.4, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /tmp, inifile:
plugins: beakerlib-0.7.1, leapp-0.8.1
collected 0 items                                                                                                         

============================================== no tests ran in 0.00 seconds ===============================================
```
**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
Fedora release 29 (Twenty Nine)
- `# uname -a`
Linux menpad 5.2.11-100.fc29.x86_64 #1 SMP Thu Aug 29 12:52:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):
```
$ rpm -qa 'leapp*' 'python*-leapp*'
leapp-deps-0.8.1-100.201909191012Z.85c9791.master.fc29.noarch
python3-leapp-0.8.1-100.201910021534Z.20036ad.master.fc29.noarch
```

**Additional context**
It might be wise to include special initialization inside leapp module. But if no module is included, it should not block any unrelated script placed somewhere under git clone.

**Comment by bocekm** [comment]
@pemensik, what library are you trying to test? leapp-repository shared or actor library? If so, in such a library you need to include leapp framework python modules.
If you run pytest in any folder within leapp-repository directory structure, it picks up the pytest configuration file leapp-repository/conftest.py which call the leapp framework to load the leapp-repository.
Are you suggesting to make the conftest.py smarter and not call the leapp framework when you try run `pytest x.py` where the x.py does not include anything leapp framework-related?

**Comment by bocekm** [comment]
@examon, I've created RHELLEAPP-1869 to deal with this. On top of backlog ;)

**Comment by pemensik** [comment]
I am trying to test my own bind configuration parser. It is much faster to test basic library in separate test. It is also much faster to debug it. Then without modification, test it as leapp library in second step.

I would suggest to move framework initialization into separate module. Make for example import leapp.test, which would initialize complete environment. Not only it always configures leapp. Problem is it cannot handle exception in its configuration, even no single leapp module was imported. Or try to hook it into leapp module. If any submodule is imported, it is fine. But it should not block simple scripts, where such failure is not an error.

I think it should trigger error only on loading leapp namespaces provided by leapp-repository. Maybe it could define function for repo initialization, which would change some value in leapp.actor and/or leapp.libraries.actor module? It would be called for any importing such modules, but would be skipped for unrelated scripts.

**Comment by bocekm** [comment]
@pemensik, can I close the issue based on https://github.com/oamg/leapp-repository/pull/367?

**Comment by bocekm** [comment]
Seems like done.

**Comment by pemensik** [comment]
No, actually that fix was just handbrake. It did not fix primary issue. It just provided a way to work around.

I have problem with import system of actors in project. It is hard to develop fragments of Actors on Fedora box, because no packages are provided. And unnecessary dependencies on repository itself. But I will open new issue when I am able to formulate better why I think current import path system is broken. For now, It is just difficult to use PYTHONPATH to have imports working. Why is there some virtual leapp.libraries.common, when such file is not directly provided?
More later

**Comment by pirat89** [comment]
> Why is there some virtual leapp.libraries.common, when such file is not directly provided?

Not sure what do you mean by that. It's possible that I missed the point, so in case you find my point completely unrelated to the topic, just ignore it. But I believe this is better than write people they have to watch into the repository to find out what path they should use - instead of something you can refer simply and people can find it, doesn't matter name of repositories. Similar thing for actor. Imagine that every actor would need different import paths. Imagine you want the hierarchy structure of repositories. Why to use long nonsense imports? After time, I thing this is very elegant solution in regards to generic structure of [leapp repositories](https://leapp.readthedocs.io/en/latest/repository-dir-layout.html).

But as I told, it's possible that I missed the point. Still, when you formulate properly your problem in a new issue, it will be easier to discuss it, fix it or find a way to improve the experience. But in case that imports are problematic, it's issue for leapp - not leapp-repository.
