### ISSUE TITLE
storageinfoscanner parsing error

### ISSUE THREAD

**Issue by shaded-enmity** [oamg/leapp-repository#387]
The parser expects each line of the mount command to contain up to 6 entries separated by space. This wrong since the path to the target mount point can contain spaces. E.g.:

```
/dev/sr0 on /run/media/user/RHEL-7.6 Server.x86_64 type iso9660 (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,mode=0400,dmode=0500,uhelper=udisks2) 
```

**Comment by shaded-enmity** [comment]
Viable alternative could be reading `/proc/mounts` since spaces are properly escaped there there:
```
/dev/loop2p1 /mnt/foo\040bar iso9660 ro,nosuid,nodev,relatime,nojoliet,check=s,map=n,blocksize=2048 0 0
```

**Comment by pirat89** [comment]
Finally we can see, whether this has been real scenario or not.
