### ISSUE TITLE
Update contribution guidelines - code style, actor's description

### ISSUE THREAD

**Issue by bocekm** [oamg/leapp-repository#41]
Style guide:
- the use of a trailing comma in tuples with only one element, e.g. `produces = (MyModelTag,)`
- what specific style of multiline docstring to use (PEP257 does not dictate one style or another)

The description should be separated in two: brief overview description for users (displayable in a list of actors, e.g. in Cockpit) and thorough behavioral description for devels and testers. Mention that the behavioral description of an actor should serve not only for component test developers but also for E2E test devels/QEs.

**Comment by bocekm** [comment]
```
class MyActor(Actor):
    """
    This is a lengthy
    multiline docstring.
    """
    name = 'my_actor'

    def process(self):
       """Short one-line docstring."""
       mutliline_string_variable = (
           'I am a multiline string.\n'
           'This is my second line.'
       )
```

**Comment by bocekm** [comment]
@vinzenz, @shaded-enmity, on Cabal we have agreed on the following multiline string formatting, which is actually incorrect as it includes whitespaces you most of the times don't want:
```
class MyClass():
    multiline_attribute = '''
        I hold some lengthy
        multiline string.
    '''
```
Take a look if you fancy the alternative formatting I used above. I think it's better than:
```
mutliline_string_variable = 'I am a multiline string.\n' \
                            'This is my second line.'
```
I fear neither look pythonic enough for you. If so, propose another.

**Comment by vojtechsokol** [comment]
What about this for multiline strings?:
```python
multiline_string = ('first line',
                    'second line')
```

And regarding multiline docstring, why not use [PEP257](https://www.python.org/dev/peps/pep-0257/)? I.e. for one liner a phrase (ending in a period) with opening and closing quotes on the same line and for multi-line docstring the first line would be the same phrase, followed by a blank line, followed by a more elaborate description:
```python
class SimpleClass(Object):
    """This is a simple class."""

class ComplicatedClass(Object):
    """
    This is a more complicated class.

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc porta sed
    urna venenatis faucibus. Phasellus at bibendum ligula, a posuere metus.
    """

**Comment by bocekm** [comment]
The `multiline_string` you propose is actually a tuple. So, yeah, in general I'm for the parenthesis version as well as I mentioned two comments above.

As to the use of PEP257, the thing is that it allows a bit of variations: _"The summary line may be on the same line as the opening quotes or on the next line."_
We'll allow just "on the next line". I guess that's the only difference. So I'll leave the PEP257 in the contribution guidelines, and just mention this one difference.

So, to wrap it up, here's the string & docstring formatting:
```python
class MyActor(Actor):
    """
    Start with a single-line brief summary of the actor (under the triple quotes).

    Leave a blank line below the summary and then describe the actor's behaviour
    here in detail.
    """
    name = 'my_actor'

    def process(self):
        """This is a simple method."""
        complicated_method()

    def complicated_method():
        """
        This is a more complicated method.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc porta sed
        urna venenatis faucibus. Phasellus at bibendum ligula, a posuere metus.
        """
        mutliline_string = (
            'I am a multiline string.\n'
            'This is my second line.'
        )
```
