### ISSUE TITLE
API docs missing/broken on readthedocs.io

### ISSUE THREAD

**Issue by tomato42** [oamg/leapp-repository#445]
**Actual behavior**

Links to class definitions on some pages of documentation lead to 404 page.

**To Reproduce**

1. go to https://leapp.readthedocs.io/en/latest/best-practices.html#use-convenience-exceptions-to-stop-the-actor-s-execution
2. click `StopActorExecution` link
3. See error

**Expected behavior**
class documentation for `StopActorExecution`

**System information (please complete the following information):**

Firefox 72.0.1 on Fedora 30

****

**Additional context**

**Comment by bocekm** [comment]
Thans for reporting it. That's probably because of a change in a way readthedocs render the pages. I'll fix it.
