### ISSUE TITLE
[RFE] Give more info than "unsupported OS"

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp-repository#466]
**Actual behavior**

When I schedule upgrade from 7.6, I get inhinbit:

    ============================================================
                               ERRORS                           
    ============================================================

    2020-03-09 07:32:07.110274 [ERROR] Actor: verify_check_results
    Message: Unsupported OS

    ============================================================
                           END OF ERRORS                        
    ============================================================

**To Reproduce**
Steps to reproduce the behavior

 1. Get RHEL-7.6
 2. subscribe to CDN
 3. install leapp (from master)
 4. run `LEAPP_DEVEL_RPMS_ALL_SIGNED=1 LEAPP_UNSUPPORTED=1 leapp upgrade --debug`
 5. See error

**Expected behavior**

Say more about what leapp does not like about my OS.  (Is it the
source OS or target OS?  What *is* supported?)

**System information (please complete the following information):**

 *  RHEL-7.6
 *  `Linux some-host.redhat.com 3.10.0-957.27.2.el7.x86_64 #1 SMP Tue Jul 9 16:53:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

    leapp-0.9.0-100.202003021951Z.69f3f8c.master.el7_6
    leapp-repository-0.9.0-100.202003051725Z.5e21253.master.el7_6

**Comment by pirat89** [comment]
@AloisMahdal have you opened the generated report? There should be specified the reason. People are required to check the generated report and the title message to get all information. Anyway, the message could be changed to something like: "The installed OS is not supported for in-place upgrade to RHEL 8".

**Comment by bocekm** [comment]
Partial improvement: RHELLEAPP-2113

**Comment by AloisMahdal** [comment]
#472 is already a good enough improvement for me.  Closing this. Thanks!
