### ISSUE TITLE
repository_mapping error on valid map file

### ISSUE THREAD

**Issue by TimeToFixStuff** [oamg/leapp-repository#492]
Attempting an upgrade from RHEL 7.8 to RHEL 8, I extracted the files at
https://access.redhat.com/articles/3664871

...and continued with the leapp upgrade. I made sure the files got created and their content is what is in the compressed file.

This is the error I got:

                         ERRORS
============================================================

2020-04-22 21:46:12.694263 [ERROR] Actor: repository_mapping
Message: The repository mapping file is invalid, offending line number: 3 (need more than 7 values to unpack). It is possible the file is out of date.
Summary:
    Hint: Read documentation at the following link for more information about how to retrieve the valid file: https://access.redhat.com/articles/3664871
2020-04-22 21:46:19.887423 [ERROR] Actor: pes_events_scanner
Message: Cannot parse RepositoriesMap data properly
Summary:
    Problem: Did not receive a message with mapped repositories

============================================================
                       END OF ERRORS

**Comment by bocekm** [comment]
Hi, thanks for the report. The _pes-events.json_ and _repomap.csv_ files currently available at https://access.redhat.com/articles/3664871 are not compatible with the latest upstream version (builds available at https://copr.fedorainfracloud.org/coprs/g/oamg/leapp/builds/). The files are compatible with builds available through Red Hat Subscription Management (RHSM).

There's currently no public way of getting the latest files compatible with the latest upstream version. 

The new version 0.10.0 will be available through RHSM with the [release of RHEL 8.2](https://www.redhat.com/en/blog/whats-new-red-hat-enterprise-linux-82). At that time, also the _pes-events.json_ and _repomap.csv_ files will be updated at https://access.redhat.com/articles/3664871. After that happens, you'll be able to use these updated files with the latest upstream version. So, stay tuned.

**Comment by TimeToFixStuff** [comment]
Can I force installation of some combination of an sos version and the leapp 0.9.x version? Currently, the sos plugin conflicts with sos and will not install along side it.

**Comment by pirat89** [comment]
@TimeToFixStuff why would you do that, when 0.9.x supports only RHEL 7.6 for update? I think that any experiments in this way do not worth for the result. I suggest you to wait a little. As you see in the article that @bocekm shared, it will be soon.

**Comment by bocekm** [comment]
@TimeToFixStuff, if you've got conflicts between sos and leapp, there's no working combination. Remove sos first. The conflict will be resolved with the 0.10.0 that will be available through RHSM with the release of RHEL 8.2.
