### ISSUE TITLE
Actors with names which are substring of the other actors fails to import their libs

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp-repository#547]
**Actual behavior**
When import of persistentnetconfig happens the ImportError raised (see https://travis-ci.org/github/oamg/leapp-repository/jobs/712894638#L1176)

**To Reproduce**
Create an actor with the name which is a substring of another actor

https://travis-ci.org/github/oamg/leapp-repository/jobs/712894638#L1176

**Expected behavior**
No error should happen

**Comment by ZhukovGreen** [comment]
ref #526

**Comment by pirat89** [comment]
@ZhukovGreen  this should be fixed in `leapp`. I think it's kind of regression as this sounds familiar to me. @vinzenz

**Comment by ZhukovGreen** [comment]
@pirat89 I don't understand this, sorry. The fix applies solely to the leapp-repository way of injecting the actor context for testing purposes. The leapp uses another way of testing actors, so how is this related?

**Comment by pirat89** [comment]
@pirat89 ah. You are probably right. I just remember we have been discussing that in the past and that probably very same error was in the leapp as well.

**Comment by ZhukovGreen** [comment]
@pirat89 ok
