### ISSUE TITLE
Rephrase excluded msgs report

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp-repository#552]
Excerpt from a report message:
```
The list of these packages (repositories: codeready-builder-for-rhel-8-x86_64-rpms):
- python3-pyxattr
```

This is just a bit confusing. I'd change it to:
```
The list of these packages together with the excluded repository they are available in:
- python3-pyxattr: codeready-builder-for-rhel-8-x86_64-rpms
```

_Originally posted by @bocekm in https://github.com/oamg/leapp-repository/pull/543_

**Comment by bocekm** [comment]
What falls under the same bucket is also this message:
```
Title: Packages will not be installed
Summary: 4 packages will not be installed or upgraded due to repositories unknown to leapp:
- libselinux-python3
- postfix-cdb
- postfix-pcre
- postfix-sqlite
```
We should state next to each package, what is the repository unknown to leapp.

**Comment by ZhukovGreen** [comment]
Solving it in a new MR (not in https://github.com/oamg/leapp-repository/pull/554) . But it will be stacked on top of the mentioned one @bocekm
