### ISSUE TITLE
run linters only for python3 (experiment)

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp-repository#563]
Rationale:
Outputs of linters from python2 and python3 are usually identical and if there is some minor difference, then it is neglectable or marked as ignored.
If there could be a little chance to trap into some python2 very specific issue, then it is assumed to be captured by unit tests or verification tests.

Under scope:
- [ ] update the ci to run linters only for python3

**Comment by pirat89** [comment]
During the time this PR has been created, I remember at least one issue that has been caught by one of linters and missed by the other one. We are going to keep Py2 linters as long as we have to keep our code Python2 compatible.
