### ISSUE TITLE
create templates for new issues

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp-repository#571]
todo

**Comment by pirat89** [comment]
Hmm :) Man, we have already templates for new issues :)

**Comment by ZhukovGreen** [comment]
@pirat89 We have only 1 template and the task description assumes more than 1 template (template**S**):)

**Comment by pirat89** [comment]
That's the question, whether we need more templates.

**Comment by pirat89** [comment]
Cleaning the opened issues. So closing this one as it's probably out-of-date and the description is msising.
