### ISSUE TITLE
Create actor which will check the data from the previous two actors and optionally inhibit upgrade if needed

### ISSUE THREAD

**Issue by zhukovgreen** [oamg/leapp-repository#596]
Ref #593 

------------

Acceptance criteria:
- [x] if the driver on the host machine is unavailable on a target system - then the upgrade should be inhibited #602
- [x] if ... unsupported, but available - then the upgrade should continue with a warning (based on a talk with Rob Evers, the answerfile shouldn't be used. The reason is that this case is very typical, and they would like to avoid the big intensity of customer requests.) #602
- [x] Implement a dict like attribute for leapp models https://github.com/oamg/leapp/pull/672

**Comment by ZhukovGreen** [comment]
@oamg/developers: is it ok for us do not use the answerfile when the driver is available, but not supported on a target system?

**Comment by pirat89** [comment]
Already done.
