### ISSUE TITLE
env shebang in nm-update-client-ids.py

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp-repository#72]
**Actual behavior**

Tool embedded with `NetworkManagerUpdateClientId` actor contains *env* based shebang, which is against packaging guidelines.

**To Reproduce**

>     $ cd /usr/share/leapp-repository/repositories/system_upgrade/el7toel8
>     $ grep '^#!/.*env' -R
>     actors/networkmanagerupdateclientid/tools/nm-update-client-ids.py:#!/usr/bin/env python

**Expected behavior**

No env-based shebang.  Most probably `#!/usr/bin/python` is the right one, although I'm not 100% sure

**System information (please complete the following information):**

 *  *leapp-repository-0.5.0-1.201902121352Z.34c2486.master.el7_5.noarch*

**Comment by AloisMahdal** [comment]
Here's the guideline:

 *  https://fedoraproject.org/wiki/Features/SystemPythonExecutablesUseSystemPython

although I suspect there's more relevant RHEL-7 version of it.

**Comment by pirat89** [comment]
Good catch

**Comment by vinzenz** [comment]
Is going to be fixed by https://github.com/oamg/leapp-repository/pull/69

Thanks for reporting anyway. In case we will need this.

**Comment by AloisMahdal** [comment]
Looks like #69 died and this is still not fixed.  Is this low-hanging enough for hack week? ;-)

**Comment by pirat89** [comment]
@AloisMahdal  https://github.com/oamg/leapp-repository/pull/117 - just moved to the new PR. Not sure why, but doesn't matter

**Comment by AloisMahdal** [comment]
The PR is merged, but a of leapp-repository-0.6.0-1.201904151130Z.8d87204.master.el7_6, the shebang is still there --- just the actor was renamed.

was:

    /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/networkmanagerupdateclientid/tools/nm-update-client-ids.py

is now:

    /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/networkmanagerupdateconnections/tools/nm-update-client-ids.py

**Comment by pirat89** [comment]
bad reviewer :(

**Comment by examon** [comment]
Fixed in the #155
