### ISSUE TITLE
Freeing up space does not change the `1311MB more space needed` error

### ISSUE THREAD

**Issue by CleanCut** [oamg/leapp-repository#784]
**Actual behavior**

No matter how much space I free up on `/`, I get the following error, that says I need _exactly_ 1311MB more space freed up.:

```
Error Summary
-------------
Disk Requirements:
   At least 1311MB more space needed on the / filesystem.
```

**To Reproduce**

I dunno how you could possibly reproduce my setup. My server's like...7 or 8 years old, originally CentOS 6, then upgraded to CentOS 7. So, I guess:

1. Run `leapp upgrade` on my old CentOS 7 server.
2. See error

**Expected behavior**
> A clear and concise description of what you expected to happen.

Well, originally I had 15GB free, so I figured I needed to free up...1311 more megabytes. So, as I freed up space, I expected the error to complain less (or not at all).  But I now have 25GB free, which is approx 10 times more than it said it needed "more", but the error remains identical.

**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
```
$ cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)
```
- `# uname -a`
```
$ uname -a
Linux hardware.agileperception.com 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):

```
$ rpm -qa "*leapp*"
leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-upgrade-el7toel8-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
leapp-deps-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-upgrade-el7toel8-deps-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
leapp-data-almalinux-0.1-2.el7.noarch
python2-leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
```

> Attach (or provide link to) log files if applicable (optional - may contain confidential information):
> 
> - *All files in /var/log/leapp*
> - */var/lib/leapp/leapp.db*
> - *journalctl*
> - If you want, you can optionally send anything else would you like to provide (e.g. storage info)
> 
> **For your convenience you can pack all logs with this command:**
> 
> `# tar -czf leapp-logs.tgz /var/log/leapp /var/lib/leapp/leapp.db`
> 
> Then you may attach only the `leapp-logs.tgz` file.

☝🏻 That's an odd recommendation, since GitHub won't accept a file with that extension. 🤨 

- [journalctl.txt](https://github.com/oamg/leapp-repository/files/7800255/journalctl.txt)
- [leapp-logs.zip](https://github.com/oamg/leapp-repository/files/7800261/leapp-logs.zip)

****

**Additional context**
> Add any other context about the problem here.

```
$ df -h
Filesystem                        Size  Used Avail Use% Mounted on
devtmpfs                           16G     0   16G   0% /dev
tmpfs                              16G     0   16G   0% /dev/shm
tmpfs                              16G  9.7M   16G   1% /run
tmpfs                              16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/centos_hardware-root   50G   26G   25G  51% /
/dev/sdb1                         745G   80G  665G  11% /images
/dev/sda2                         494M  289M  205M  59% /boot
/dev/sda1                         200M   12M  189M   6% /boot/efi
/dev/mapper/centos_hardware-home  423G  3.8G  419G   1% /home
tmpfs                             3.2G   12K  3.2G   1% /run/user/42
tmpfs                             3.2G     0  3.2G   0% /run/user/0
```

**Comment by pirat89** [comment]
Hi @CleanCut, as you have XFS formatted without `ftype`, a special workaround is applied to be able to use containers on your system. Skipping technical details, you have to set the `LEAPP_OVL_SIZE` envar to give it enough space for the download of all packages. See more [here](https://leapp.readthedocs.io/en/latest/el7toel8/envars.html#leapp-ovl-size). That will resolve the problem.

**Comment by CleanCut** [comment]
Thanks! doing `export LEAPP_OVL_SIZE=4096` and re-running worked!
