### ISSUE TITLE
leapp-preupgrade.log should be preserved

### ISSUE THREAD

**Issue by brianjmurrell** [oamg/leapp-repository#812]
**Actual behavior**
`/var/log/leapp/leapp-preupgrade.log` is removed from the upgraded system

**To Reproduce**
1. Stand up a CentOS 7.9 machine
2. Run `leapp preupgrade` and observe that `/var/log/leapp/leapp-preupgrade.log` exists
3. Run `leapp upgrade` and complete the upgrade
4. Once rebooted into the upgraded O/S observe that `/var/log/leapp/leapp-preupgrade.log` no longer exists

**Expected behavior**
`/var/log/leapp/leapp-preupgrade.log` should be preserved so that the the upgrade result can be audited against it to ensure that what was done during pre-upgrade was done during upgrade

**System information (please complete the following information):**

- OS and version: CentOS 7.9
- `Linux server.interlinx.bc.ca 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
  leapp-upgrade-el7toel8-deps-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
  leapp-upgrade-el7toel8-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
  leapp-deps-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
  python2-leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
  leapp-data-almalinux-0.1-2.el7.noarch

**Comment by pirat89** [comment]
This is expected behaviour. You can find the preupgrade log (with all other logs) inside the archive.
