### ISSUE TITLE
package leapp-0.14.0-1.el8_6.noarch requires python3-leapp = 0.14.0-1.el8_6, but none of the providers can be installed

### ISSUE THREAD

**Issue by saper** [oamg/leapp-repository#911]
**Actual behavior**

This machine runs Red Hat Enterprise Linux 8.6 upgraded from RHEL 7.9 some time ago.

```
$ rpm -qa |grep leapp
python2-leapp-0.11.1-1.el7_9.noarch
leapp-repository-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch
leapp-0.11.1-1.el7_9.noarch
leapp-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch
leapp-repository-0.12.0-2.el7_9.noarch
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.6 (Ootpa)
# dnf upgrade
Error:
 Problem 1: package leapp-0.14.0-1.el8_6.noarch requires python3-leapp = 0.14.0-1.el8_6, but none of the providers can be installed
  - package python3-leapp-0.14.0-1.el8_6.noarch conflicts with python2-leapp provided by python2-leapp-0.11.1-1.el7_9.noarch
  - cannot install the best update candidate for package leapp-0.11.1-1.el7_9.noarch
  - problem with installed package python2-leapp-0.11.1-1.el7_9.noarch
 Problem 2: package python3-leapp-0.14.0-1.el8_6.noarch requires leapp-framework-dependencies = 5, but none of the providers can be installed
  - package leapp-upgrade-el8toel9-0.16.0-6.el8_6.noarch requires leapp-framework >= 2.2, but none of the providers can be installed
  - package leapp-upgrade-el8toel9-0.16.0-6.el8_6.noarch requires python3-leapp, but none of the providers can be installed
  - installed package leapp-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch obsoletes leapp-deps provided by leapp-deps-0.14.0-1.el8_6.noarch
  - cannot install the best update candidate for package leapp-repository-0.12.0-2.el7_9.noarch
  - problem with installed package leapp-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**To Reproduce**
Steps to reproduce the behavior

1. RHEL 8 upgraded from RHEL 7
2. leapp is left installed
3. after June 2022 try `dnf update`

**Expected behavior**
Either

1. Leapp should be left alone and does not inhibit other packages
or
3. Leapp should be upgraded to the 7to8 to the 8to9 version

**System information (please complete the following information):**

- OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
- `# uname -a`

      Linux some.corp.subscribed.to.rhel.satellite 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):
````
$ rpm -qa "*leapp*"
python2-leapp-0.11.1-1.el7_9.noarch
leapp-repository-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch
leapp-0.11.1-1.el7_9.noarch
leapp-deps-el8-5.0.0-100.202004161145Z.de6626f.master.el8.noarch
leapp-repository-0.12.0-2.el7_9.noarch
````

**Comment by saper** [comment]
Manual removal of el7to8 leapp works, but shouldn't be needed.

**Comment by pirat89** [comment]
@saper Hi. Thanks for the report.  Actually it is not a bug as the manual removal in this case is not only needed, but also required - as documented in the official documentation, chapter [post-upgrade steps](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#performing-post-upgrade-tasks-rhel-7-to-rhel-8_upgrading-from-rhel-7-to-rhel-8). We need to state that manual post-upgrade actions are (and will be) required in 100% of any in-place upgrade. One of these steps require the manual removal of remaining RHEL 7 packages.

In case of the in-place upgrade, leapp packages must always remain the whole upgrade procedure (as that's requirement to be able to finish the upgrade) so it needs to be removed manually after the upgrade performed by leapp is finished. So we actually used several mechanisms to ensure that leapp related packages cannot be upgraded (dnf configuration to exclude any operations with leapp packages, set conflicts between packages).
