### ISSUE TITLE
Use of leapp with megaraid drivers

### ISSUE THREAD

**Issue by kludgeaudio** [oamg/leapp-repository#913]
The megaraid_sas drivers are no longer provided as part of the release distribution for Oracle Linux 8.  This is no problem if your operating system disc is on a different controller; you can upgrade it with leapp and then install the drivers off elrepo.  That goes fine.

However, if the disk itself is on a megaraid controller, the installation procedure seems to work but then it cannot boot into the upgrade-initramfs because there's no megaraid_sas driver rolled into that kernel.

Since Dell is still selling machines that require this driver today, I think dropping support for it was foolish on the part of the Oracle folks, but sadly I can do nothing about that.

Is there an official workaround for this?

**Comment by vinzenz** [comment]
Thanks for the suggestion, we will take this in consideration for future improvements around this topic. There are multiple shortcuts taken at the moment, a proper analysis if the upgrade is actually affected by various restrictions, as is this one, might be added in future.
It is a very time consuming change, from analysis, implementation and testing POV, so it is rather a good idea to unmount the drives and unload the driver in the meantime.

**Comment by pirat89** [comment]
Well, we are not familiar with particular drivers nor with OL. We are familiar and we test upgrades just on RHEL. Regarding RHEL, we can share with you this link (https://access.redhat.com/discussions/3722151) with pretty long discussion about these drivers on RHEL 8 (not from the upgrade pov) so you can check whether you find an answer you are looking for. Regarding our information, some megaraid_sas drivers have been added back in RHEL 8.4+ as unsupported.

So it depends whether the particular driver is available on OL 8 in your case or not (that's what you need to discuss with your distribution vendor) - or whether there is a third party driver provided for the particular el8 kernel.

---
In case you find that particular one driver is possible to use on RHEL 8:
Another thing is that the driver might be needed to be part of the upgrade initramfs. If it is not part of it by default but you find it's present on particular OL 8 system, it will be need to add such a driver to the upgrade initramfs (and than to the target OL 8 initramfs). Definitelly something doable creating custom actors, but it could be pretty tricky now. We expect to provide in future a functionality that will make adding of particular / third-party drivers possible in a simple way (still required creation of custom actors) but not sure when we get there.

**Comment by kludgeaudio** [comment]
The driver itself is available through elrepo and I can install it after the fact... it's just that it's not being integrated into the install when it boots into the upgrade kernel.  How do I get that to get added in the install process?
--scott
________________________________
From: Petr Stodůlka ***@***.***>
Sent: Monday, June 27, 2022 8:03 AM
To: oamg/leapp-repository ***@***.***>
Cc: Dorsey, Scott B. (LARC-D316)[AEGIS] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [oamg/leapp-repository] Use of leapp with megaraid drivers (Issue #913)


Well, we are not familiar with particular drivers nor with OL. We are familiar and we test upgrades just on RHEL. Regarding RHEL, we can share with you this link (https://access.redhat.com/discussions/3722151<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faccess.redhat.com%2Fdiscussions%2F3722151&data=05%7C01%7Cscott.b.dorsey%40nasa.gov%7C08fc21cf5ef548deb98208da583501fe%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637919281936436874%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yh%2BGBMuW4AxTr%2F0wWfpU%2BNxGlksHn2wdZJfyxxHhK88%3D&reserved=0>) with pretty long discussion about these drivers on RHEL 8 (not from the upgrade pov) so you can check whether you find an answer you are looking for. Regarding our information, some megaraid_sas drivers have been added back in RHEL 8.4+ as unsupported.

So it depends whether the particular driver is available on OL 8 in your case or not (that's what you need to discuss with your distribution vendor) - or whether there is a third party driver provided for the particular el8 kernel.

________________________________

In case you find that particular one driver is possible to use on RHEL 8:
Another thing is that the driver might be needed to be part of the upgrade initramfs. If it is not part of it by default but you find it's present on particular OL 8 system, it will be need to add such a driver to the upgrade initramfs (and than to the target OL 8 initramfs). Definitelly something doable creating custom actors, but it could be pretty tricky now. We expect to provide in future a functionality that will make adding of particular / third-party drivers possible in a simple way (still required creation of custom actors) but not sure when we get there.

**Comment by pirat89** [comment]
Well, you would need to create custom actors now that will basically regenerate the initramfs again. But let's say in most hacky way, you could just update this [script](https://github.com/oamg/leapp-repository/blob/663fe43d3079c5c5950661921293afcaa43346d8/repos/system_upgrade/common/actors/initramfs/upgradeinitramfsgenerator/files/generate-initram.sh#L84) (IIRC, on the system: `/etc/leapp/repos.d/system_upgrade/common/actors/initramfs/upgradeinitramfsgenerator/files/generate-initram.sh`)

adding `--add-driver` option with expected param.
Also, it's highly possibly you will need to handle that later for the target initramfs as well to be able to boot to the system after the upgrade (https://github.com/oamg/leapp-repository/blob/663fe43d3079c5c5950661921293afcaa43346d8/repos/system_upgrade/common/actors/initramfs/targetinitramfsgenerator/libraries/targetinitramfsgenerator.py#L76).

---
Additionally from what you wrote, you will need to add & enable the specific repository where the driver is present and install an rpm I guess. For the repo and how to create/add custom actors look at here:
* https://access.redhat.com/articles/4977891

Regarding the custom actor, you will want to do something like [here](https://github.com/oamg/leapp-repository/blob/663fe43d3079c5c5950661921293afcaa43346d8/repos/system_upgrade/el8toel9/actors/cryptopoliciescheck/libraries/cryptopoliciescheck.py#L25) -- just the actor should be executed e.g. during the `ChecksPhase` (`ChecksPhaseTag`)
* produce the msg `TargetUserSpaceUpgradeTasks(install_rpms=['your-rpm'])`
* and produce the msg  RpmTransactionTaks(to_install=['your-rpm'])

This will ensure the rpm(s) will be installed during the upgrade and inside the targetuserspace container (where the upgrade initramfs is created).

**Comment by markohrastovec** [comment]
I just upgraded an IBM server with MegaRaid driver today. I believe UEK kernel from Oracle Linux still suports megaraid sas.

**Comment by pirat89** [comment]
The possibility to add drivers to the upgrade (& target) initramfs  has been added by #1081 (see the template of the custom actor in the description). That should resolve this issue - well, it needs still some manual customisations, but our goals was to provide the possibility to deal with it.
