### ISSUE TITLE
Nginx module is getting downgraded from nginx-1.20 to nginx1.14 when I migrate from centos7 to Rocky linux 8

### ISSUE THREAD

**Issue by shruthidharani-4313** [oamg/leapp-repository#999]
I am doing an leapp upgrade to move from centos7 to rockylinux8 and I see nginx-1.20 and nginx-filesystem-1.20 in centos7 is downgraded to nginx-1.14 in rockylinux8. I am using 0.12 version of leapp package.

centos7:
```
nginx-1.20.1-2.el7.x86_64
nginx-filesystem-1.20.1-2.el7.noarch
```

rockylinux8:
```
nginx-mod-http-xslt-filter-1.14.1-9.module+el8.4.0+542+81547229.x86_64
nginx-all-modules-1.14.1-9.module+el8.4.0+542+81547229.noarch
nginx-mod-http-perl-1.14.1-9.module+el8.4.0+542+81547229.x86_64
nginx-mod-mail-1.14.1-9.module+el8.4.0+542+81547229.x86_64
nginx-filesystem-1.14.1-9.module+el8.4.0+542+81547229.noarch
nginx-mod-stream-1.14.1-9.module+el8.4.0+542+81547229.x86_64
nginx-mod-http-image-filter-1.14.1-9.module+el8.4.0+542+81547229.x86_64
nginx-1.14.1-9.module+el8.4.0+542+81547229.x86_64
```

I am now installing latest nginx in rockylinux8 manually by enabling the module 1.20 using `dnf module enable nginx:1.20` and doing `yum upgrade nginx`. Is there any approach/support given in leapp procedure to do this step somehow in the leapp upgrade/preupgrade process itself instead of doing this manually after entire upgrade is done. I have tried running dnf module enable nginx:1.20 and dnf upgrade nginx via an actor in RPMUpgradePhase tag, but it seems to be not working. Because in RPMUpgradePhase tag, my actor is getting executed first i e, before the dnftransactionupgrade actor where there only nginx package is moved to el8 version. So I am not sure whether same dnf commands will work after dnftransactionupgrade actor. If so can someone help me how to define the custom actor which i am creating to be executed after dnftransactionupgrade actor or in the postRPMUpgradePhase.

It would be really helpful if someone helps me with this 
and possibly please provide references or link some documentation on your answer. Thanks in advance!!

**Comment by vinzenz** [comment]
https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/common/models/rpmtransactiontasks.py

You need to produce this message in the facts phase specifying to enable the module stream nginx 1.20

It's not a bug though, it rather seems like to me that your pes data isn't pointing to the right module stream
